version: "3.8"

services:
  app:
    build:
      context: ./services/php
    container_name: php_app
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
      - ./services/mysql/my.cnf:/etc/mysql/my.cnf

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  db_data:
